pipeline {
  agent any

  environment {
    DOCKER_HUB_USER  = 'tommy034'
    IMAGE_NAME       = 'todo-app'
    DOCKER_HUB_CREDS = 'docker-hub-credentials'
  }

  stages {

    stage('Checkout') {
      steps {
        // pull your repo into workspace
        git branch: 'main', url: 'https://github.com/ZweNyanWin/ZweNyanWin.github.io.git'
        sh 'ls -la'
        sh 'ls -la jenkins-app || true'
      }
    }

    stage('Install') {
      steps {
        dir('jenkins-app') {
          sh 'ls -la'
          sh 'npm install'
        }
      }
    }

    stage('Test') {
      steps {
        dir('jenkins-app') {
          sh 'npm test || echo "No tests / skipping"'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('jenkins-app') {
          sh "docker build -t ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest ."
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: "${DOCKER_HUB_CREDS}",
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
          sh "docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest"
        }
      }
    }
  }

  post {
    always {
      sh 'docker logout || true'
      sh "docker rmi ${DOCKER_HUB_USER}/${IMAGE_NAME}:latest || true"
    }
  }
}

